{{- if and .Values.backupPersistence.enabled (not .Values.backup.s3.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rusmes.fullname" . }}-backup
  labels:
    {{- include "rusmes.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - {{ .Values.backupPersistence.accessMode }}
  {{- if .Values.backupPersistence.storageClass }}
  storageClassName: {{ .Values.backupPersistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backupPersistence.size }}
{{- end }}
---
{{- if and .Values.config.search.enabled .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rusmes.fullname" . }}-search
  labels:
    {{- include "rusmes.labels" . | nindent 4 }}
    app.kubernetes.io/component: search
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
